# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll
title: Harish Karthic

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Harish Karthic

description: Stylish Jekyll Theme
author:
  name: Harish Karthic
  email: hkarthicb@gmail.com
  github: hkarthik7
  # twitter: dbtek
  # pinterest: asd123
  linkedin: harish-karthic-b
  bio: Azure DevOps Engineer and Automation Enthusiast 
  # email_md5: 726351295ec82e145928582f595aa3aa

rss_path: sitemap.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate